### ISSUE TITLE
Enable Nuts node integration

### ISSUE THREAD

**Issue by woutslakhorst** [nuts-foundation/nuts-monitor#2]
- [x] #12
- [x] add configuration option for nuts-node address and API authentication
- [x] #9
- [x] #16
- [x] add connection check to health check API
- [x] add health check to docker image

items on the list may be converted to issues for progress tracking
