### ISSUE TITLE
Add landing page that views diagnostics of local node

### ISSUE THREAD

**Issue by woutslakhorst** [nuts-foundation/nuts-monitor#4]
- [ ] add client API (generated) to Nuts node
- [ ] add backend API for frontend to get data from 
- [ ] add a menubar to the left
- [ ] add 'dashboard' page that shows key numbers in large fonts, with fancy colors and boxes
